
export const APP_NAME = "Ytdown.Soraa";
export const ORIGIN = 'https://ssvid.net';

export const translations = {
  id: {
    heroTitle: "Download Video YouTube Gratis",
    heroDesc: "Konversi video YouTube ke MP4 & MP3 dengan kualitas terbaik secara instan. Tanpa batas, tanpa iklan, dan sangat cepat.",
    placeholder: "Tempel link YouTube di sini...",
    btnDownload: "Download",
    btnPaste: "Tempel",
    history: "Sesi Terakhir",
    clear: "Bersihkan",
    features: "Fitur Unggulan",
    about: "Tentang Kami",
    faq: "Pusat Bantuan",
    privacy: "Kebijakan Privasi",
    terms: "Syarat & Ketentuan",
    support: "Hubungi Admin",
    converting: "Sedang Memproses...",
    wait: "Tunggu sebentar",
    get: "Unduh Sekarang",
    recent: "Terakhir Dilihat",
    noHistory: "Belum ada riwayat unduhan.",
    errorCORS: "Gagal memproses. Pastikan link YouTube valid atau coba lagi nanti.",
    articleTitle: "Ytdown Soraa adalah mesin ekstraksi media tercanggih yang dibangun untuk kecepatan dan efisiensi total.",
    articleSubtitle: "KECEPATAN, KEAMANAN, DAN KUALITAS TANPA KOMPROMI",
    articleBody1: "Kami mengerti waktu Anda berharga. Teknologi konversi kami dirancang untuk memproses file media hanya dalam hitungan detik, bukan menit.",
    articleBody2: "Tanpa iklan yang mengganggu dan tanpa pelacakan data. Ytdown Soraa menawarkan lingkungan yang bersih dan aman untuk semua kebutuhan media Anda.",
    stepTitle: "CARA DOWNLOAD SUPER CEPAT",
    step1: "Salin link video dari aplikasi atau website YouTube.",
    step2: "Tempelkan link pada kolom input yang tersedia di atas.",
    step3: "Klik tombol Download dan pilih resolusi favorit Anda.",
    feature1Title: "Akses Universal",
    feature1Desc: "Dukungan penuh untuk semua perangkat tanpa biaya tambahan sepeserpun.",
    feature2Title: "High Quality Audio",
    feature2Desc: "Ekstrak audio jernih hingga 320kbps untuk pengalaman mendengarkan terbaik.",
    feature3Title: "Tanpa Registrasi",
    feature3Desc: "Nikmati layanan kami secara anonim tanpa perlu mendaftar akun.",
    feature4Title: "Bebas Iklan",
    feature4Desc: "Kami mengutamakan kenyamanan Anda dengan antarmuka yang bersih dari iklan."
  },
  en: {
    heroTitle: "Free YouTube Video Downloader",
    heroDesc: "Convert YouTube videos to MP4 & MP3 with the best quality instantly. No limits, no ads, and ultra-fast processing.",
    placeholder: "Paste YouTube link here...",
    btnDownload: "Download",
    btnPaste: "Paste",
    history: "Recent Sessions",
    clear: "Clear All",
    features: "Premium Features",
    about: "About Us",
    faq: "Help Center",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    support: "Contact Support",
    converting: "Processing...",
    wait: "Please wait",
    get: "Download Now",
    recent: "Recently Viewed",
    noHistory: "No download history found.",
    errorCORS: "Process failed. Please ensure the link is correct or try again later.",
    articleTitle: "Ytdown Soraa is the most advanced media extraction engine built for pure speed and efficiency.",
    articleSubtitle: "SPEED, SECURITY, AND QUALITY WITHOUT COMPROMISE",
    articleBody1: "We know your time is valuable. Our conversion technology is engineered to process media files in seconds, not minutes.",
    articleBody2: "No intrusive ads and zero data tracking. Ytdown Soraa offers a clean and secure environment for all your media needs.",
    stepTitle: "SUPER FAST DOWNLOAD STEPS",
    step1: "Copy the video link from the YouTube app or website.",
    step2: "Paste the link into the input field above.",
    step3: "Click the Download button and choose your preferred quality.",
    feature1Title: "Universal Access",
    feature1Desc: "Full support for all devices without any additional fees.",
    feature2Title: "High Quality Audio",
    feature2Desc: "Extract crystal clear audio up to 320kbps for the best experience.",
    feature3Title: "No Registration",
    feature3Desc: "Enjoy our services anonymously without needing an account.",
    feature4Title: "Zero Intrusive Ads",
    feature4Desc: "We prioritize your comfort with a clean, ad-free interface."
  }
};
